name: comparus
services:
  db1:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init-db1.sql:/docker-entrypoint-initdb.d/init-db.sql

  db2:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init-db2.sql:/docker-entrypoint-initdb.d/init-db.sql

  comparus:
    image: comparus
    ports:
    - 8080:8080


