name: comparus
services:
  db1:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql

  comparus:
    image: comparus
    ports:
    - 8080:8080
    depends_on:
    - db1
