name: comparus
services:
  db1:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
    volumes:
    - ./init-db1.sql:/docker-entrypoint-initdb.d/create_database.sql

  db2:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433
    volumes:
    - ./init-db2.sql:/docker-entrypoint-initdb.d/create_database.sql

  comparus:
    image: comparus
    ports:
    - 8080:8080
    depends_on:
    - db1


