server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

data-sources: 
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://db1/postgres
    table: users  
    user: postgres   
    password: postgres
    mapping: 
     id: user_id
     username: login
     name: first_name     
     surname: last_name
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://db2/postgres
    table: users  
    user: postgres   
    password: postgres
    mapping: 
     id: user_id
     username: login
     name: first_name     
     surname: last_name
